# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stocks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stocks

 pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
 pod 'Kingfisher', '~> 7.0'
 pod 'CocoaLumberjack'
 
end
